CREATE TABLE `DOCUMENTOS` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `TITULO` VARCHAR(150) NOT NULL,
  `TIPO` ENUM(indicacion,informacion) NOT NULL,
  `CEDULA_PACIENTE` VARCHAR(8) NOT NULL,
  `FECHA_EMISION` DATE NOT NULL,
  `RUTA_ARCHIVO` VARCHAR(150) UNIQUE NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1
);

INSERT INTO DOCUMENTO (TITULO, TIPO, CEDULA_PACIENTE, RUTA_ARCHIVO) 
VALUES ('ESTUDIO VIRUELA DEL MONO', 'informacion', 58491927, 'documentos/informacion/EVDM.pdf'); 

INSERT INTO DOCUMENTO (TITULO, TIPO, CEDULA_PACIENTE, RUTA_ARCHIVO) 
VALUES ('GUIA HERRAMIENTAS QUIRURGICAS', 'indicacion', 58487612, 'documentos/indicacion/CIRUGIA_MATERIALES.pdf'); 

INSERT INTO DOCUMENTO (TITULO, TIPO, CEDULA_PACIENTE, RUTA_ARCHIVO) 
VALUES ('PRESCRIPCION MEDICACION ANTIBIOTCO FLUCENAZOL', 'indicacion', 55651822, 'documentos/indicacion/ANTIBIOTICO_FLUCENAZOL.pdf');
